### ISSUE TITLE
Add `data-strong` and `data-tone`

### ISSUE THREAD

**Issue by royalicing** [RoyalIcing/tela#1]
See Badges from Seek OSS: https://seek-oss.github.io/braid-design-system/components/Badge/

Strong:
- Normal (no attribute) or strong (`<button data-strong>`)

Tone:
- Positive (`<button data-tone=positive>`)
- Promote (`<button data-tone=promote`)
- Info (`<button data-tone=info>`)
- Neutral (`<button data-tone=neutral>`)
- Caution (`<button data-tone=caution>`)
- Critical (`<button data-tone=critical>`)

```css
[data-tone] {
  color: var(--tone-color-strong);
  background-color: var(--tone-color);
}
[data-strong][data-tone] {
  color: white;
  background-color: var(--tone-color-strong);
}

[data-tone=positive] {
  --tone-color: var(--color-positive);
  --tone-color-strong: var(--color-strong-positive);
}

[data-tone=promote] {
  --tone-color: var(--color-promote);
  --tone-color-strong: var(--color-strong-promote);
}
```

----

Or:

```css
[data-tone=positive] {
  color: var(--color-strong-positive);
  background-color: var(--color-positive);
}

[data-strong][data-tone=positive] {
  color: white;
  background-color: var(--color-strong-positive);
}

[data-tone=promote] {
  color: var(--color-strong-promote);
  background-color: var(--color-promote);
}

[data-strong][data-tone=promote] {
  color: white;
  background-color: var(--color-strong-promote);
}
```
